export default {
  CONTACT_SELECT: 'CONTACT_SELECT',
  CONTACT_EDIT_VIEW_SELECT: 'CONTACT_EDIT_VIEW_SELECT',
  CONTACT_CHANGE: 'CONTACT_CHANGE',
  CONTACT_SAVE: 'CONTACT_SAVE',
  CONTACTS_REQUEST: 'CONTACTS_REQUEST',
  CONTACTS_RECEIVE: 'CONTACTS_RECEIVE'
}
